In [1]:
# We have imported numpy and pandas libraries.
# We have imported linear_model library which is used for linear regression

In [2]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [3]:
# We are conduct csv file and then showing the output of the file

In [20]:
data=pd.read_csv("Desktop/homeprices.csv")
data

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [21]:
# We are training our model in LinearRegression
# We have 1 independent variable area and 1 dependent variable price

In [22]:
MyTable = linear_model.LinearRegression()
MyTable.fit(data[["area"]],data[["price"]])

LinearRegression()

In [23]:
# We are predicting the value of dependent variable(price) with the help of independent variable(area)

In [24]:
MyTable.predict([[3200]])

array([[612082.93153327]])

In [25]:
# We are conduct the coefficient of our independent variable

In [26]:
MyTable.coef_

array([[167.30954677]])

In [27]:
# We are conduct the value of our intercept 

In [28]:
MyTable.intercept_

array([76692.38187078])

In [29]:
# Here the predicted value using the calculation of equation mx + c

In [30]:
167.30954677*3200+76692.38187078

612082.9315347801

In [31]:
from sklearn.metrics import mean_squared_error

In [32]:
# We are finding the mean_squared_error  [between original price and predicted price ]

In [33]:
mean_squared_error([610000],[612082.93153327],squared = False)

2082.93153327005