In [1]:
# We have imported numpy and pandas libraries.
# We have imported linear_model library which is used for linear regression

In [2]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [3]:
# We are conduct csv file and then showing the output of the file

In [5]:
data=pd.read_csv("Desktop/simple_li_homeprices.csv")
data

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  595000
4  4000  760000
5  4100  810000

In [6]:
# We are training our model in LinearRegression
# We have 1 independent variable area and 1 dependent variable price

In [7]:
MyTable = linear_model.LinearRegression()
MyTable.fit(data[["area"]],data[["price"]])

LinearRegression()

In [8]:
# We are predicting the value of dependent variable(price) with the help of independent variable(area)

In [9]:
MyTable.predict([[3200]])

array([[612082.93153327]])

In [10]:
# We are conduct the coefficient of our independent variable

In [11]:
MyTable.coef_

array([[167.30954677]])

In [12]:
# We are fetching the value of our intercept 

In [13]:
MyTable.intercept_

array([76692.38187078])

In [14]:
# Here is the predicted value using the calculation of equation mx + c

In [15]:
167.30954677*3200+76692.38187078

612082.9315347801

In [16]:
from sklearn.metrics import mean_squared_error

In [17]:
# We are finding the mean_squared_error (the error between original price and predicted price )

In [18]:
mean_squared_error([610000],[612082.93153327],squared = False)

2082.93153327005