In [2]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr1)

[1 2 3 4 5 6 7]


In [3]:
#type of array
print(type(arr1))

<class 'numpy.ndarray'>


In [4]:
#array from tuple
import numpy as np
arr2 = np.array((1, 2, 3, 4, 5))
print(arr2)

[1 2 3 4 5]


In [5]:
#0-D array
import numpy as np
d0 = np.array(42)
print(d0)


42


In [7]:
#1-D array
import numpy as np
d1 = np.array([1, 2, 3, 4, 5])
print(d1)

[1 2 3 4 5]


In [8]:
#2-D array
import numpy as np
d2 = np.array([[1, 2, 3], [4, 5, 6]])
print(d2)

[[1 2 3]
 [4 5 6]]


In [9]:
#3-D array
import numpy as np
d3= np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(d3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [11]:
#check dim of array
import numpy as np

a= np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)

2
3


In [12]:
#Higher Dim Array
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=8)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[[[[1 2 3 4]]]]]]]]
number of dimensions : 8


In [14]:
#Access Array Elements
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2])

3


In [16]:
#Access 2-D Arrays
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2nd dim: ', arr[1, 4])

5th element on 2nd dim:  10


In [17]:
#Access 3-D Arrays
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


In [18]:
#Slicing arrays
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])

[2 3 4 5]
[5 6 7]
[1 2 3 4]


In [20]:
#Negative Slicing
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


In [21]:
#Slicing 2-D Arrays

import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [23]:
#Data Type of array
import numpy as np
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [24]:
#Creating Arrays With a Defined Data Type
import numpy as np
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [25]:
#VIEW
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
k = arr.view()
arr[0] = 31
print(arr)
print(k)

[31  2  3  4  5  6  7]
[31  2  3  4  5  6  7]


In [26]:
#COPY
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
d = arr.copy()
arr[0] = 42
print(arr)
print(d)

[42  2  3  4  5]
[1 2 3 4 5]


In [27]:
#Shape of an Array
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [28]:
#Join Arrays

import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [29]:
#Join two 2-D arrays along rows
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [30]:
#Sort Array
import numpy as np
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
